dateModified: 1570628553
email:
  fromEmail: development@modernmedia.ca
  fromName: $SITE_NAME
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  d08a0d16-0e00-49e6-9cd4-465fa2d65d7d:
    name: Errors
  efc44cb8-5a29-4f4b-8977-cf6ee112e601:
    name: Common
fields:
  a5cb77be-c4d9-4d3e-88fb-d5384ca13941:
    name: 'Error Image'
    handle: errorImage
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: ''
      defaultUploadLocationSource: 'volume:7ecd1ebd-978a-4658-b737-afe3333fc256'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:7ecd1ebd-978a-4658-b737-afe3333fc256'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources:
        - 'volume:7ecd1ebd-978a-4658-b737-afe3333fc256'
      source: null
      targetSiteId: null
      viewMode: large
      limit: '1'
      selectionLabel: ''
      localizeRelations: false
      validateRelatedElements: ''
    contentColumnType: string
    fieldGroup: d08a0d16-0e00-49e6-9cd4-465fa2d65d7d
  b8ba7115-3804-4c06-8a96-501963d1fc5c:
    name: 'Error Headline'
    handle: errorHeadline
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: d08a0d16-0e00-49e6-9cd4-465fa2d65d7d
  e6d658aa-c335-4f15-bbcd-59fe05d9e913:
    name: 'Error Text'
    handle: errorText
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: '1'
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: d08a0d16-0e00-49e6-9cd4-465fa2d65d7d
plugins:
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-optimize:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  neo:
    edition: standard
    enabled: true
    schemaVersion: 2.2.0
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.8
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  wordsmith:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0.0
  guide:
    edition: lite
    enabled: true
    schemaVersion: 2.0.0
    settings:
      templatePath: _guide
      assetVolume: dcbd85d8-6f4d-48bb-854f-63a188dae698
      clientName: $SITE_NAME
      myCompanyName: HAWK
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  linkit:
    edition: standard
    enabled: true
    schemaVersion: 1.0.8
  navigate:
    edition: standard
    enabled: true
    schemaVersion: 2.4.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  templatecomments:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
sections:
  54e60257-f31a-44aa-960e-bbd364197e28:
    name: Homepage
    handle: homepage
    type: single
    enableVersioning: false
    propagationMethod: all
    siteSettings:
      feebb077-de74-4f70-86d6-5cfb99820eba:
        enabledByDefault: true
        hasUrls: true
        uriFormat: __home__
        template: index
    entryTypes:
      fb3a8f31-d1cc-4c13-903b-a501f7e51f54:
        name: Homepage
        handle: homepage
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
  a72bfe0c-3389-4f9f-8ec1-ab318ec10b29:
    name: Errors
    handle: errors
    type: channel
    enableVersioning: false
    propagationMethod: all
    siteSettings:
      feebb077-de74-4f70-86d6-5cfb99820eba:
        enabledByDefault: true
        hasUrls: false
        uriFormat: null
        template: null
    entryTypes:
      faceb3ed-6771-453c-9c2a-aa330847f6db:
        name: Errors
        handle: errors
        hasTitleField: true
        titleLabel: Title
        titleFormat: null
        sortOrder: 1
siteGroups:
  17e20f8c-8423-49a1-b90f-5b633c44727e:
    name: $SITE_NAME
sites:
  feebb077-de74-4f70-86d6-5cfb99820eba:
    baseUrl: $SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: $SITE_NAME
    primary: true
    siteGroup: 17e20f8c-8423-49a1-b90f-5b633c44727e
    sortOrder: 1
system:
  edition: solo
  name: Imperial
  live: true
  schemaVersion: 3.3.3
  timeZone: America/Halifax
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  7ecd1ebd-978a-4658-b737-afe3333fc256:
    name: Site
    handle: site
    type: craft\volumes\Local
    hasUrls: true
    url: '@assetsUrl/assets/site'
    settings:
      path: '@webroot/assets/site'
    sortOrder: 2
  dcbd85d8-6f4d-48bb-854f-63a188dae698:
    name: Guide
    handle: guide
    type: craft\volumes\Local
    hasUrls: true
    url: '@assetsUrl/assets/guide'
    settings:
      path: '@webroot/assets/guide'
    sortOrder: 1
